repos:
- repo: local
  hooks:
    - id: nixfmt
      name: nixfmt
      entry: nixfmt
      language: system
      files: \.nix$
      pass_filenames: true
    - id: black
      name: black
      entry: black
      args: ["./bin/dot"]
      language: system
      pass_filenames: false