onboarding = false
[theme]
auto_switch = true
dark_name = "rose-pine"
light_name = "rose-pine-dawn"

[update]
version_check = false

[keys]
focus_pane_left = "prefix+left"
focus_pane_down = "prefix+down"
focus_pane_up = "prefix+up"
focus_pane_right = "prefix+right"

[ui]
show_agent_labels_on_pane_borders = false
agent_panel_sort = "priority"
